# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: students
        uri: http://localhost:8082
        predicates:
        - Path=/api/v1/students/**
      - id: schools
        uri: http://localhost:8083
        predicates:
        - Path=/api/v1/schools/**
server:
  port: 8085
